### ISSUE TITLE
Call to undefined function Pdp\idn_to_ascii()

### ISSUE THREAD

**Issue by spy23** [C-Sparrow/Tartana#46]
On my Synology and on OS X with MAMP I get the following error: 

Fatal error: Call to undefined function Pdp\idn_to_ascii() in /Users/stefanb/Sites/tartana/vendor/jeremykendall/php-domain-parser/src/Pdp/Parser.php on line 318

I think this function is not available when PHP is compiled w/o --enable-intl. Is it possible to catch this error?

**Comment by C-Sparrow** [comment]
See my solution here https://forum.synology.com/enu/viewtopic.php?f=20&t=91099&p=425790#p425790. I'v also contacted their support and the response was that they are using the limited PHP 5.6 version for their own apps.
We are using a library to parse url, so catching is not really an alternative. Normally enable-intl should be enabled.

Somehow we are dealing with similar problems as pyload has on installation on Synology NAS devices https://github.com/pyload/pyload/issues/2584.
